### ISSUE TITLE
Function-level linking

### ISSUE THREAD

**Issue by vadimcn** [WebAssembly/tool-conventions#15]
Are there any plans to support function-level linking?   If so, how?   Would relocatable webassembly modules be allowed to contain multiple data and code sections?

**Comment by vadimcn** [comment]
cc @sbc100

**Comment by dschuff** [comment]
I think we do want to support use cases like `-ffunction-sections` which sounds pretty similar to what you are asking about. As you say, we'd need to support multiple data/code sections, or to have sufficient intelligence in the linker to do true function-level linking.

A disadvantage of multiple code sections would be that the object file would no longer be a "valid" wasm binary. (Up to now, the binaries have been valid according to wasm's binary spec, even if they are not actually runnable without relocation). We could possibly work around that by just having the extra code sections be custom sections (we'd have to be careful to generate the right info in the other sections, e.g. types, because they would be unreferenced by the "real" CODE section but that doesn't seem too bad).

True function-level linking might be appealing, although it might not mesh well with lld's architecture, not sure.

**Comment by vadimcn** [comment]
> I think we do want to support use cases like -ffunction-sections which sounds pretty similar to what you are asking about.

Yes, that's exactly what I am asking about.

> True function-level linking might be appealing, although it might not mesh well with lld's architecture, not sure.

I'm pretty sure this would involve disassembling the code into wast.   This is very possible in the case of WebAssembly, but I was under impression that lld would like to be able to simply concatenate code sections, otherwise they'd just disassemble them and not need any relocations.

Given the above constraint, multiple code sections seem like the next best option.  I suppose compilers could also emit a module per function, but that would significantly deviate from traditional compilation workflow.

**Comment by sbc100** [comment]
I don't think we necessarily need multiple code sections to do this.  The lld port currently does simply concatenate code sections, but it would be simple enough to add an argument where it would instead concatenate individual functions without requiring disassembly of the code within the functions.   Something like -mstrip-unused-functions.  The fact that traditional toolchains use a compiler flag to trigger this behaviour is kind of an implementation detail .. if we want to inherit this we could add a bit to the linking metdata section of the objects that are compiled with -mfunction-sections.

**Comment by vadimcn** [comment]
I don't know much about the binary encoding of wasm modules, but if you can just concatenate functions without disassembling them, that'd be fantastic!

**Comment by sbc100** [comment]
The linker internally now operates on a per-function basis, but --gc-sections still isn't implement yet.
