### ISSUE TITLE
Document relationship between TLS and bulk memory

### ISSUE THREAD

**Issue by penzn** [WebAssembly/tool-conventions#184]
In [D130053](https://reviews.llvm.org/D130053#3677262) @sbc100 pointed out that LLVM needs bulk memory for TLS support, because that is how TLS segments are emitted as weak segments and require `memory.init`.

I don't know if it is going to be possible to implement TLS without bulk memory, say less efficiently. This might need to be documented here - Linking.md has a section on TLS and threads, but it doesn't say anything about bulk memory.

**Comment by sbc100** [comment]
Regarding building an alternative: I think that while it might be possible to do TLS via memcpy() instead of memory.init, its almost certainly not worth the effort because the intersections of engines that support threads and engines that don't support bulk memory is likely to be empty.

In fact bulk-memory is about it be enabled by default: https://reviews.llvm.org/D125728

**Comment by penzn** [comment]
Turns out there is a description in Linking.md, I got confused by the "TLS to MVP" section. I've opened a PR to move those sections together (somehow I can't request reviews).

**Comment by dschuff** [comment]
I invited you to join the WebAssembly Github organizatoin. I think that should allow you to request reviews.

**Comment by penzn** [comment]
Thank you, accepted the invite! It doesn't look like I can request yet though.
