### ISSUE TITLE
Export of local symbols in .o files

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/tool-conventions#29]
This C:
```c
static void foo(void) {}
void *bar(void) { return foo; }
```
currently compilers to this wasm:
```wasm
(module
  (type (;0;) (func (result i32)))
  (type (;1;) (func))
  (func $bar (type 0) (result i32)
    i32.const 0)
  (func $foo (type 1))
  (table (;0;) 1 anyfunc)
  (memory (;0;) 0)
  (export "bar" (func $bar))
  (export "foo" (func $foo))
  (elem (i32.const 0) $foo))
```
It's surprising to see "~~bar~~foo" exported here, since it has internal name linkage. The linkage is recorded in the metadata, via `WASM_SYM_BINDING_LOCAL`, however it seems like it would be more wasm-like to just omit the export.

Local symbols are never comdat or weak and they don't have visibilities, so it seems like they could be omitted from the WASM_SYMBOL_INFO subsection altogether.

**Comment by binji** [comment]
You mean `foo` right?

**Comment by sunfishcode** [comment]
Yes; updated.

**Comment by sbc100** [comment]
This is mostly for compatibility with other formats.  Local symbols are visible in the symbol table of ELF and appear in the output of `nm` for example:
```
$ nm  test.o 
0000000000000006 T bar
0000000000000000 t foo
```

The imports + exports is how we model the symbol table itself, so the only way to name a symbol right now is via an import or an export.

Also, although relocations point to globals and functions (not imports and exports), its helpful if there is a symbol name associated.   One the name section expands to include naming things other than functions we could revisit this.

Since the expected use case for these objects is as input to the linker I don't really see problem here.  The local symbols will not be exported in the linked binary.

**Comment by sunfishcode** [comment]
Thanks. I agree; it's not urgent.

For completeness, here's the link to the proposal to expand the name section: https://github.com/WebAssembly/design/pull/1064.

**Comment by sbc100** [comment]
My current thinking is that we drop the NAME section completely from the object format, and only use it for the final binary.  For the object format we want to more advanced concept of the symbol table.  I'll open two new issues for (a) dropping NAME section from clang output files (b) creating a more advanced symbol table.
