### ISSUE TITLE
Linking.md: How to handle calls to weakly defined functions

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/tool-conventions#46]
We need to find a way to handle the following pattern, specifically in case where foo() is not defined at link time:

```
int foo() __attribute__((weak));

int main() {
  if (&foo) {
    return foo();
  }
  return 0;
}
```

Currently llvm will generate a call instruction to foo and a relocation at the call site to inject the function index.   If foo turns out to be undefined at link time there is no valid function which the linker can insert.

@NWilson and I have discuess a few possible options (see https://reviews.llvm.org/D44028):

1. Have the linker error out.  This seems bad as the above code is valid and should link.
2. Have the linker generate a synthetic function that abort (i.e. contains only an unreachable) and use the index of the synthetic function here.  The doenside is that this adds complexity to the linker and that it would need to generate a new function for each signature.
3. Have llc always emit call_indirect when calling weak references.  Then bad FUNCTION_INDEX relocations against weak symbols in the object format.

(3) seems like the nicest so long as it is feasilbe in llvm and that use increased use of call_indirect doesn't cause a performance drop.  My guess is that weak symbols are not that common, but it also seems valid to assume that declaring a symbol as weak should not have a runtime overhead.

**Comment by sbc100** [comment]
See https://reviews.llvm.org/D44028

**Comment by binji** [comment]
Can the compiler generate the synthetic function instead? If there is a naming convention, it can just use that to find the correct one.

**Comment by sbc100** [comment]
Interesting.  That could work.  I think @NWilson 's current linker patch doesn't add to much complexity, but maybe having the compiler do it would mean less synthetic function generation in the linker.  The cost would be that we'd need to define some kind of convention.  i.e.  "For each weak undefined the symbol there much be an accompanying defined symbol that the linker can use".. this could be a naming convension or it could be in the symbol table it self.

**Comment by NWilson** [comment]
For the record - I initially wanted (3) and wrote a patch on that basis. Then I changed my mind (based on thoughts from Sam) and went for (2) instead.

If we can do it in the linker, we should do it in the linker, since it's then more "universal", making fewer assumptions about the origin of the of the linker's inputs. If we solved the problem in LLC, we'd still have to do something about it in the linker to check/validate the input file, and we'd have to mention the corner-case in Linking.md (whether to allow or disallow it, the spec needs to say). So whatever we do it'll infect the linker, may as well keep LLC out of the mess if it doesn't have to be involved. That was my eventual thinking anyway. Just doing it in the LLC is probably the least fuss overall, even though it might not be the least fuss in LLD specifically.

NB: Bugzilla link to issue reported there in Jan: https://bugs.llvm.org/show_bug.cgi?id=36039

**Comment by dschuff** [comment]
Is the linker currently already generating the `wasm_nullptr` function (i.e. the thing that gets index 0 in the table)? Having the linker generate dummy weak functions isn't too much different from that, is it? Presumably they could even use the same stubs?

**Comment by sbc100** [comment]
For the null table entry there is no need to generate anything, we simply leave the entry empty to get the desired effect.

**Comment by binji** [comment]
@NWilson I had the same thought about patching the call into unreachable. I kind of like this idea, but patching to a synthesized function that traps is probably clearer, assuming we can get a stack trace.

**Comment by NWilson** [comment]
The idea of patching the entire call instruction rather than just the SLEB operand is ugly because it would introduce a third "type" of relocation (5-byte SLEB / 4-byte I32 / 6-byte CALL) for not very good reasons. More code overall I'd reckon, since it hooks deeper into LLC.

The better messaging and nicer stack traces for the "stub" approach are another plus ("error: trap in function __undefined" or similar would at least indicate that something was undefined).

**Comment by sbc100** [comment]
This is now fixed I think. Via linker-generated stubs.

**Comment by NWilson** [comment]
Thanks! The corresponding update to Linking.md needs to be merged in https://github.com/WebAssembly/tool-conventions/pull/47
