### ISSUE TITLE
Linking.md function relocations

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/tool-conventions#5]
I haven't looked at globals yet, but here's what I've found looking at the function relocations in Linking.md and implementing them in LLVM MC:

 - W need a relocation code for (non-leb128) function addresses in the data section.
 - For function addresses used in i32.const and the data section, the index is the function table index, not the function index.
 - R_FUNCTION_INDEX_[S]LEB relocations need an index field too, to identify a function.

**Comment by sbc100** [comment]
1. For function addresses in the data section, yes I think you are correct.
2. I'm not quite sure what you mean by "function table index" vs "function index", can you explain?
3. For R_FUNCTION_INDEX_[S]LEB the plan was to read the existing value to find the function index, no?

**Comment by sbc100** [comment]
One thing I found while writing the prototype wasm-link tool in wabt was that it might make sense to relocations to stored as a tuple of "section" + "offset" that was its was easy to relocation one section at time since you know exactly which relocation pertain to given section.

Essentially partitioning the relocations by the section that they apply to.  Does that makes sense to you?

**Comment by dschuff** [comment]
2. "Function index" is in the space consisting of all the module's imports plus all the module's defined functions, in that order. "Function table index" is the index in the `WebAssembly.Table` (aka the module's indirect function table), i.e. the function's "address" as seen by C code. non-address-taken functions and imports aren't in that table.
3. I think that's the intention of the current wording. Although in the ELF world there has been a transition away from REL to RELA relocations where the addend is used instead of reading the data section. I imagine that reading the index from the relocation rather than from the text section might make linking faster.

**Comment by dschuff** [comment]
wrt 2, I'll also add that the function index space is used in call instructions, and the function table is used in data contexts (data section and i32.const instructions).

For your last question, in ELF, IIRC there's typically a separate relocation section corresponding to each section that needs relocations applied (i.e. all the relocations for `.text` are in `.rela.text`). That would remove the need for an extra field which would have a lot of duplication.

**Comment by dschuff** [comment]
(oh also, the section header in a relocation section has a field that says which section the relocations apply to. We'll probably need some kind of header for relocation sections too). see also https://docs.oracle.com/cd/E23824_01/html/819-0690/chapter6-94076.html#scrolltoc

**Comment by sbc100** [comment]
OK.  So it sounds like it would make sense to generate a seperate relocation section for each known section that requires relocations.   Why do you think the explicit addend is a good idea?  Surely that would just be duplicating data, no?  And any code that processes the relocation would need to write the relevant location anyway so there doesn't seem to be a cost to first reading it.    I suppose it makes tools like `nm` and `objdump` able to give more information about the relocations without reading the section data they apply too?

**Comment by sbc100** [comment]
@sunfishcode, are you ok with moving to one reloc section per section.  This is how my wabt linker prototype is shaping up.

**Comment by sunfishcode** [comment]
Yes, that sounds good to me. We'll eventually need relocation for debug info sections too, so having "which section is this relocation in" factored out sounds good.
