### ISSUE TITLE
Referring to other sections in linking metadata

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/tool-conventions#52]
There is currently only one place where we need to do this:  In the reloc sections when we specify the section to which the relocations are to be applied: https://github.com/WebAssembly/tool-conventions/blob/master/Linking.md#relocation-sections

But we are about to add another for WASM_SYMBOL_TYPE_SECTION: https://reviews.llvm.org/D44184

In the existing code the method used to refer to another sections is by "section code + optional string if code is 0".   This has several downsides:

- it means you can't have multiple custom sections with the same name
- it makes the code and API messy/complex
- its a waste of space to duplicate these strings in the binary

To see how to makes the code complex look at the proposed to change WasmSymbolInfo.  It would be much nicer to simpy reuse the existing ElementIndex field here.

So I propose that we refer to sections instead by their index within the module.  This would be a new index space used only my the linking metadata fields.

The only downside to doing this AFAICT is that it would mean tools that blindly insert/remove sections in the middle of the file would break that metadata sections.  Looks at the ELF spec, they already have this problem and the tools are built to rewrite index when they do that kind of thing.

**Comment by sbc100** [comment]
@sunfish and I discussed this at the CG meeting, and we could see both side.

@yurydelendik we talking about this on IRC recently too.

**Comment by sbc100** [comment]
Proposed change https://github.com/WebAssembly/tool-conventions/pull/53

**Comment by NWilson** [comment]
Looks a sensible change. It's more compact, and any tools that mess around with sections can just fix up the indexes (which isn't necessarily easy, since the indexes are embedded inside custom sections). This does mean that parsing/interpreting the reloc custom sections becomes mandatory for tools: no longer can tools just look at the sections they care about (if the tool is trying to insert a new section), it will have to unpack some custom sections in order to fix up their contents. In practice it's not a problem: reloc sections are well-known specced sections, and all existing Wasm tools understand them, so it seems sensible.

**Comment by sbc100** [comment]
https://reviews.llvm.org/D45980
