### ISSUE TITLE
Atomic fence support

### ISSUE THREAD

**Issue by aheejin** [WebAssembly/tool-conventions#59]
C++ 11 provides [`std::atomic_signal_fence`](https://en.cppreference.com/w/cpp/atomic/atomic_signal_fence) and [`std::atomic_thread_fence`](https://en.cppreference.com/w/cpp/atomic/atomic_thread_fence), and LLVM IR's [`fence`](http://llvm.org/docs/LangRef.html#fence-instruction) instruction also takes a [`syncscope`](http://llvm.org/docs/LangRef.html#syncscope) argument, which can be either `"singlethread"` (for a single thread, such as signal handlers) or `"<target-scope>"` (for multiple threads). And there are people who use `asm volatile(""::: "memory")` with a similar usage to fences. How do we support these fences in wasm? Some discussions have been going on in this [CL](https://reviews.llvm.org/D49194), but the CL itself was not very much related to the topic.

---

#### [`std::atomic_thread_fence`](https://en.cppreference.com/w/cpp/atomic/atomic_thread_fence) / LLVM's `fence syncscope("<target-scope>")`
Wasm does not have a fence instruction, and currently all atomic memory instructions are sequentially consistent, but we still need something because fences also order non-atomic instructions. I submitted a [CL](https://reviews.llvm.org/D50277) that converts a fence into a sequence of
```
get_global $__stack_pointer
i32.atomic.rmw.or 0
```
which is basically an idempotent atomic RMW instruction.

---

#### [`std::atomic_signal_fence`](https://en.cppreference.com/w/cpp/atomic/atomic_signal_fence) / LLVM's `fence syncscope("singlethread")`
Currently [the fence CL](https://reviews.llvm.org/D50277) does not distinguish syncscopes, treating both of them the same way conservatively. But for fences that work only within a thread, we may not need to emit an atomic idempotent RMW instruction; preventing instruction reordering across it during the backend compilation (using a pseudo instruction or something) would be sufficient, and it can eventually be lowered down to 0 instruction. What do you think? 

---

#### `asm volatile(""::: "memory")`
We are currently doing nothing for this, but how about treating this as the same way as a signal fence, meaning it will become a pseudo instruction that prevents reordering within the compiler backend but eventually be converted to 0 instruction?

**Comment by aheejin** [comment]
@dschuff @jfbastien @sunfishcode @conrad-watt
I guess not adding CC list in the issue post itself would be neater...

**Comment by aheejin** [comment]
@conrad-watt It was unclear in the thread proposal, but it seems like, unlike in C++, atomic operations cannot be reordered with respect to non-atomic operations in wasm. There had been a similar discussion thread in binaryen repo, starting from https://github.com/WebAssembly/binaryen/pull/1094#issuecomment-316793576. So, I guess we need something to prevent reordering, and that's why inserted an idempotent atomicrmw instruction.

**Comment by conrad-watt** [comment]
Yeah, Wasm definitely has stricter rules for atomic + non-atomic ordering. The issue linked above looks like a discussion on Wasm -> Wasm transformations, where this would be a disallowed reordering.

The current issue seems to be about the correct translation for llvm -> Wasm. Here, we start in a semantics where the reordering is allowed (llvm/C++) and (potentially after some llvm -> llvm transformations) move to one where it isn't (Wasm/JS). Once we move to Wasm-world, this naturally disallows further reorderings, even without the inserted atomic.rmw.

I'd expect to see such an instruction inserted when going in the opposite direction, from a semantics where the reordering is disallowed, to one where it is allowed. In any case, the atomic.rmw seems to have been mainly motivated in [the CL linked above](https://reviews.llvm.org/D49194) by the concern that C++ barriers cause a ordering restriction on non-atomics which must be preserved when moving to Wasm. But if I'm reading [this](https://en.cppreference.com/w/cpp/atomic/atomic_thread_fence) correctly, an additional ordering restriction on non-atomics is only imposed if they are related by  sequenced-before to a particular relaxed atomic operation that does not otherwise synchronize until forced to by the fence. But such an atomic operation, when translated to a Wasm atomic, is strengthened to the point that it will synchronize anyway, so fences could be no-ops. Consider that the synchronizes-with edges specified involving the fence [here](https://en.cppreference.com/w/cpp/atomic/atomic_thread_fence) induce ordering constraints that are weaker than those that would be introduced if the atomic actions Y and X already synchronized.

**Comment by aheejin** [comment]
> But if I'm reading this correctly, an additional ordering restriction on non-atomics is only imposed if they are related by sequenced-before to a particular relaxed atomic operation that does not otherwise synchronize until forced to by the fence.

I'm not sure about this point. Please correct me if I'm mistaken. In [this page](https://en.cppreference.com/w/cpp/atomic/atomic_thread_fence), for example for fence-atomic sync (first paragraph), it is the case when the two threads are like this:

| Thread A | Thread B |
| --- | --- |
| Insts1 (non-atomic stores) |  |
| F (release fence) |  |
| X (atomic store) |  |
|  | Y (reads X) |
|  | Insts2 (non-atomic loads) |

Wouldn't that mean, without the fence having effect, Insts1 can mix with Insts2?

**Comment by lars-t-hansen** [comment]
As a practical matter, for asm.js a fence was translated as Atomics.add(0,0), since address 0 is always writeable, ie we don't need to mess around with reading the stack pointer, unlike what Linux does for fences on older systems, and what @aheejin suggested for LLVM.

**Comment by aheejin** [comment]
@lars-t-hansen You mean, even wasm atomic semantics guarantees every atomic and non-atomic instructions' ordering is preserved wrt every atomic instructions, it emits `Atomics.add(0,0)`? Is that for user-friendliness?
And I used the value stored in `__stack_pointer` global because it is likely to be in the cache, while the address 0 is not.

**Comment by lars-t-hansen** [comment]
@aheejin, what I meant was that when the C++ source program contains an explicit fence operation, emscripten compiling to asm.js would emit Atomics.add(0,0); on current JS/asm.js implementations this would have the desired ordering effect even though the idea of a fence has no meaning in the JS memory model.

We discussed actually recognizing Atomics.add(0,0) as a special case and emitting a native fence instruction for it.  In that case, it is better for the arguments to be (0,0) since it is easy to recognize that.  But we didn't implement it for asm.js, and last week we removed atomics support from our asm.js implementation.

(What you say about the cache locality of the stack memory makes sense, of course.)

**Comment by sunfishcode** [comment]
> asm volatile(""::: "memory")

I think we all agree codegen should translate this to zero wasm instructions.

> `std::atomic_signal_fence`

One of the arguments against adding a `volatile` flag to wasm itself was that wasm doesn't (currently) have signals, so the `volatile sig_atomic_t` construct doesn't need special treatment. By similar reasoning, it seems codegen can translate `atomic_signal_fence` into zero wasm instructions too.

> `std::atomic_thread_fence`

If I'm reading @conrad-watt's comments, LLVM LangRef, and C++ correctly, this seems analogous to the situation with `volatile` loads and stores: even if we might wish to be "friendly" and emit something to prevent additional reorderings, such code is already at risk of being reordered by LLVM, so the better place for such a feature is the front-end, where we can get consistent semantics through the optimizer as well as the wasm code.

So with what I know right now, having the backend translate `atomic_thread_fence` to zero instructions also seems best.  That way it won't add any extra overhead to code that does follow the rules.

**Comment by dschuff** [comment]
I agree regarding `asm volatile(""::: "memory")` and `std::atomic_signal_fence`. We'll still need to prevent the backend from moving memory ops across the fence (e.g. MachineLICM and register stackification).  

I'm a bit more on the fence regarding `std::atomic_thread_fence`. One concern I have is that if there is a mistake in usage (e.g. the user expects the fence to prevent motion of non-atomic operations), then it's much much harder to debug or understand what's happening when it's the VM that violates the user's assumption. If the compiler does so, then the user can always disassemble the wasm binary and see what has happened to their loads and stores. However if it's the VM, then there might not be any way to see what has happened; and indeed it may be non-deterministic (e.g. based on tiering). That sounds like a bit of a nightmare.
Still, the C++11 memory model is pretty clear on what the semantics are and a user using `std::atomic_thread_fence` is writing new code and opting into that, so it seems ok to actually implement the C++11 memory model and generate no instructions. This "new code opting-in" idea is why my opinion on this case is sort of the opposite of my opinion on volatiles, which are almost certainly legacy code. 

It might be worth having some kind of debug option in either the compiler (where we would insert extra atomic RMWs or something) or the VM (disabling optimizations) to help debug in situations like this.

I guess we haven't also discussed `__sync_synchronize()`. That's intended to be a full barrier, and I think we do want to have the no-op Atomic RMW for that.

**Comment by jfbastien** [comment]
Maybe it'll be helpful to review this summary of the semantics of fence operations:
https://en.cppreference.com/w/cpp/atomic/atomic_thread_fence

**Comment by aheejin** [comment]
@dschuff 
> I guess we haven't also discussed __sync_synchronize(). That's intended to be a full barrier, and I think we do want to have the no-op Atomic RMW for that.

C++11's `std::atomic_thread_fence`, gcc's `__atomic_thread_fence`, and gcc's `__sync_synchronize` all translates to LLVM's `fence` with no syncscope (meaning it syncs with all other threads). Unlike others, `__sync_synchronize` does not take a memory order arguments, and it is translated to a `seq_cst` fence. So if we want to treat at least `__sync_synchronize` as a full memory barrier, we should treat all of these the same, which is also one reason I'm inclined to translate these to an idempotent atomicrmw instruction.

And C++11's `std::atomic_signal_fence` and gcc's `__atomic_signal_fence` translates to LLVM's `fence` with `syncscope("singlethread")`, which the current [CL](https://reviews.llvm.org/D50277) translates to a pseudo compiler barrier that eventually becomes 0 instruction.

**Comment by conrad-watt** [comment]
LLVM fence ([my ref](https://llvm.org/docs/Atomics.html)) seems to take the C++11 semantics as does __atomic_thread_fence ([my ref](https://gcc.gnu.org/onlinedocs/gcc-4.7.1/gcc/_005f_005fatomic-Builtins.html)). So the story between all of them in relation to std::atomic_thread_fence is uncomplicated.

__sync_synchronize is weird. Going by [this ref](https://gcc.gnu.org/onlinedocs/gcc-4.7.1/gcc/_005f_005fsync-Builtins.html#g_t_005f_005fsync-Builtins), it describes itself as legacy and compatible with the [Intel Itanium Processor-specific Application Binary Interface](https://www.uclibc.org/docs/psABI-ia64.pdf). Looking at 7.4 of this, it appears to intend to guarantee a full compiler and memory barrier, even for C++ non-atomics. This is hard to square with C++11's treatment of non-atomic data races. I imagine there are some really hairy legacy code issues here. I'd speculate there are even theoretically possible nutty LLVM link-time optimisations which could break the guarantee it wants to give if it's compiled to an LLVM seq_cst fence (like no-oping a fence if no atomic op can be related to it by sequence-before).

More immediately, I can totally understand why it's desirable to make sure __sync_synchronize ultimately gets compiled to an atomicrmw for Wasm. LLVM fence in isolation, semantically, doesn't need to be - but the friendliness argument seems pretty strong if __sync_synchronize becomes an LLVM fence.

**Comment by sunfishcode** [comment]
I'm not currently deeply familiar with the semantics for fences here.

My observations here are:
 - The main problem here is not wasm's problem alone, so we should generally prefer solutions that can be shared with other targets in clang.
 - This problem doesn't affect all users of LLVM.
 - Having an LLVM backend go out of its way to be friendlier than LLVM's optimizer optimizer is ultimately not that friendly, and it makes the backend harder to maintain over time.


So, I'm skeptical about doing anything "friendly" in the wasm backend.


LLVM seems pretty clear that it wants to treat `__sync_synchronize` as a `seq_cst` fence. That's what clang does with it, and that's what it says [here](http://llvm.org/docs/Atomics.html#sequentiallyconsistent).

**Comment by conrad-watt** [comment]
Ah, I didn't see that part of the doc linked by @sunfishcode. My previous comment was wrong in light of this.

There's a reasonably Wasm-specific issue here, in that the only reason C++11 fences can be a no-op in Wasm is because all Wasm atomics are sequentially consistent. This isn't true of many (any?) other targets.

**Comment by dschuff** [comment]
wrt `__sync_synchronize`, I hadn't seen Dan's link above; it does make clear LLVM intent; I was going based on https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gcc/_005f_005fsync-Builtins.html#g_t_005f_005fsync-Builtins and from my reading of that (it's admittedly vague), LLVM's intent doesn't match gcc's. But if nobody using LLVM already has complained loudly enough to get it changed, then I guess it probably doesn't matter.

Restating my thoughts above, I'm mostly OK with not being friendly and emitting no instructions for fences for now, because I think users of the C++11 fences are explicitly opting into the C++ memory model. Although I would be interested in knowing why @lars-t-hansen and co. decided to do what they did for asm.js.

Practically speaking, beyond that I'm also still worried that auto-upgrading of browsers is more likely to break code that previously worked for the same user on the same device. This is a situation that AFAIK is also unique to wasm; developers risk breakage when they upgrade their compilers, and usage of new devices could mean broken code that worked on older devices. But I don't know of any other analogous situation (other than JS on the web, of course; it's not a new problem there but this seems somehow even more likely to cause problems).

**Comment by jfbastien** [comment]
> Restating my thoughts above, I'm mostly OK with not being friendly and emitting no instructions for fences for now, because I think users of the C++11 fences are explicitly opting into the C++ memory model. Although I would be interested in knowing why @lars-t-hansen and co. decided to do what they did for asm.js.

This will break things such as the common (yet incorrect) implementation of seqlock. If you dig more you can find a bunch of fringe code which the Standard frowns upon but which the Real World supports.

**Comment by sunfishcode** [comment]
To be sure, I'm not opposed to supporting C or C++ code like this. What I'm saying is, the robust way is to translate fences as something stronger, in the frontend.

**Comment by aheejin** [comment]
@sunfishcode How can we do something from the frontend? Or, isn't the frontend doing is already sufficient? From my previous comments:
> And in this case I don't think we can do or need to do something from the frontend, because `std::atomic_thread_fence` becomes LLVM's `fence`, which provides sufficient guarantees to prevent code reordering during compilation in the middle end.

Or do you mean it's better to insert an `atomicrmw` in clang if we want that? I generally agree that in volatile's case, if we use `-fms-volatile`, it might sound clearer to users that we want change volatiles to atomics, which means effectively we reject the current semantics of normal volatiles. But in this case, replacing a `std::atomic_thread_fence` (and other legacy builtins) to an `atomicrmw` from clang and not using LLVM's [`fence`](http://llvm.org/docs/LangRef.html#fence-instruction) sounds like we even reject the semantics of LLVM's `fence` instruction, which I think is not the case. And this is also clearly a deviant behavior from all other targets, which translate `std::atomic_thread_fence` to LLVM `fence`.

**Comment by jfbastien** [comment]
Stronger fence than atomic sequentially consistent? I don't follow.

**Comment by conrad-watt** [comment]
I'm interpreting @sunfishcode as follows: if a seqcst fence does not provide the (source or IR level) semantic guarantees necessarily for seqlock to be semantically well-behaved, but compilers in practice wish to implement a compilation scheme that supports it (https://github.com/WebAssembly/tool-conventions/issues/59#issuecomment-415576918), then clearly there exists a notion of a "fence" which is stronger than a C++ seqcst fence, which corresponds to what compilers really do.

This "de-facto" semantics is something of an open research problem. But certainly if(???) we're advancing the narrative that atomics should be more aggressively optimised against their spec'd semantics, we are accepting that real-world code will break. Translating fences to atomicrmw in the Wasm backend, which is stronger than necessary, wouldn't (in principle) protect this incorrect code against earlier optimisations in the pipeline, unless the whole pipeline agreed on this "stronger than spec'd" interpretation of the fence.

**Comment by jfbastien** [comment]
Right, that's why I'm advocating for LLVM to treat the code the same as it does for other targets: clang generates a fence as always, and LLVM IR sees a fence. Nothing special for WebAssembly, just a fence. Then the WebAssembly backend has two choices: (1) emit an idempotent RMW, or (2) emit nothing. (2) breaks code such as seqlock. (1) does not, and will never break that code because the WebAssembly memory model is stronger than C++'s and LLVM's.

Seems like we should go with (1).

*if* LLVM starts breaking seqlock it'll do so for *everyone*, not just WebAssembly. This is not WebAssembly's battle to fight, and being different here only makes the platform (I count the toolchain in the platform) behave weirder and break in weird ways. We don't want that.

**Comment by aheejin** [comment]
@sunfishcode 
> That suggests that the semantics of LLVM's fence, which go by the Standard, may be insufficient for such code. Even if it happens to survive the optimizer intact today, it would be more robust [0] to have the frontend translate it into something stronger, so that it has the semantics it needs throughout the entire compilation pipeline.

If we want to translate that to `atomicrmw` in clang, we are gonna have to use `load atomic` LLVM IR instruction, which does not provide stronger guarantee than LLVM seq_cst fence. Neither of them say anything about its relationship with non-atomic operations.

Even if we come up with our own `atomicrmw` intrinsic or something, I don't think we can specify something stronger than seq_cst fence in terms of LLVM IR. All we can specify for that intrinsic is intrinsic properties, which should be from [the list of intrinsic properties](https://github.com/llvm-mirror/llvm/blob/db0f76949f25f76fc96b87b9a7b53d61c6639bb3/include/llvm/IR/Intrinsics.td#L23-L112). The reason `atomicrmw` wasm instruction works is [wasm seq_cst atomic provides stronger guarantees](https://github.com/WebAssembly/binaryen/pull/1094#issuecomment-316796667) than LLVM seq_cst atomics.

So as far as I understand, _if_ we want to be user friendly, emitting an `atomicrmw` in the backend seems to be the only way.

**Comment by sunfishcode** [comment]
@jfbastien I'd like to understand the seqlock case better. I found [this](http://www.hpl.hp.com/techreports/2012/HPL-2012-68.pdf), which is informative, though it describes multiple correct and incorrect versions. Can you describe what you mean by "the common (yet incorrect) implementation of seqlock", specifically in what it does in the reader code?

Also, in that paper, "Figure 6" is the an implementation which is claimed to conform to the C++ memory model and be efficient. If someone compiles that for wasm, and we make `atomic_thread_fence(m_o_acquire)` an `atomicrmw` in wasm (the friendly option) we'll have made the code go slow, which seems unfortunate. However, if we make `atomic_thread_fence(m_o_acquire)` a nop in wasm (the alternative), the code would seem to be about as fast as wasm can go. Is this an accurate summary?

**Comment by lars-t-hansen** [comment]
@dschuff, re asm.js I didn't do that work myself but became exposed to it because we needed something to express a fence that was in some C++ source code.  It is very likely that it was code of the sort @jfbastien is referring to, where there was a need to enforce the ordering of memory effects without having to create a synchronization edge.  Quite possibly this would have been in the translation of the Bionic libc.  I see a few fence operations in the Bionic source on github.com/aosp-mirror but this would have been several years ago so who knows what has happened with that code in the mean time.

**Comment by jfbastien** [comment]
> @jfbastien I'd like to understand the seqlock case better.

OK.

It doesn't seem like your reading needs to synchronize-with @aheejin's implementation work?

**Comment by sunfishcode** [comment]
Here's the current status of this conversation, to the best of my knowledge:

The discussion above [concluded](https://github.com/WebAssembly/tool-conventions/issues/59#issuecomment-411244864) that implementing a `seq_cst` fence as zero instructions is strictly conforming to C/C++. It's also my understanding that this is one of the reasons wasm doesn't currently have a fence instruction.

In [Hand Boehm's seqlock paper](http://www.hpl.hp.com/techreports/2012/HPL-2012-68.pdf), the example in Figure 6 describes a correct and efficient implementation. If `seq_cst` fences are lowered into heavier-weight operations, it would penalize code that takes care to use the correct and efficient technique.

And, it sounds like the specific behavior of `seq_cst` fences that real-world non-conforming code depends on is not well understood. Under these kinds of conditions, selecting conservative semantics in clang, rather than in LLVM codegen, assures that conservative semantics are applied consistently throughout the entire compilation pipeline, even if the optimizer changes to be more aggressive in the future.

With these assumptions, I propose:
 - The LLVM wasm backend lowers `seq_cst` fence into nothing.
 - We add a flag to clang to optionally make it lower a `seq_cst` fence into a volatile atomic rmw operation that otherwise has no effect, followed by a `seq_cst` fence, in LLVM IR, which is a kind of best guess as to what would be sufficient for non-conforming applications.

**Comment by conrad-watt** [comment]
One thing that I highlighted earlier is that the ability to map all fences to no-op is completely contingent on all consistencies of C/C++ atomics being mapped to Wasm `seqcst` atomics. If (when?) Wasm adds release/acquire atomics, fences could no longer automatically be no-ops. So this optimisation and any associated flags might have a limited shelf life.

**Comment by sunfishcode** [comment]
When wasm adds support for other memory orderings, would you expect it to add an explicit `fence` operation at that time?

**Comment by conrad-watt** [comment]
It might make sense to have at least `seqcst` fences. Currently fences definitely don't make sense because (as noted) Wasm atomics are already so strong that C/C++-style fences would have no effect - but with release/acquire atomics a `seqcst` fence would be semantically meaningful, and would support C/C++ compilation. The alternative would be continuing to compile fences as `seqcst` RMWs.

**Comment by conrad-watt** [comment]
I do feel that it's a little sad that, at this immediate time, carefully crafted C/C++ programs using `relaxed` atomics and fences are having to pay a performance penalty twice over during compilation to Wasm. First, their `relaxed` atomics are effectively raised to `seqcst`, and second, they must still execute an expensive "pseudo-fence", even though the only function of the fence in the source program was to cause the `relaxed` atomics to have a behaviour closer to `seqcst`.

**Comment by rossberg** [comment]
@conrad-watt:
> One thing that I highlighted earlier is that the ability to map all fences to no-op is completely contingent on all consistencies of C/C++ atomics being mapped to Wasm seqcst atomics. If (when?) Wasm adds release/acquire atomics, fences could no longer automatically be no-ops. So this optimisation and any associated flags might have a limited shelf life.

Yeah, this deeply concerns me. Basically it means that we would not be able to add other atomics without some sort of global memory-model opt-in, because we'd break existing code otherwise. That seems highly undesirable, for all the reasons that non-local semantic modes are bad and unmodular.

If we suspect that more relaxed atomics might truly be coming to Wasm eventually (which may still be an open question), would it be possible to tweak our current memory model such that it does *not* accidentally imply such a guarantee? And add some explicit fence instructions instead?

**Comment by conrad-watt** [comment]
Ah, that's an incredibly good point. The current strategy of emitting the `seqcst` RMW would be forwards-compatible in that sense, whereas my idea of eliding the barrier would be a terrible approach.

One alternative might be adding a `memory.fence` instruction to Wasm that (currently) does nothing in the formal semantics. but that implementers could choose to compile like a C/C++ SC fence, and would be forced to do so if a weaker consistency mode was added. All C/C++ fences (of any consistency) would compile to this `memory.fence`.

Since it currently does nothing, this wouldn't immediately imply any extra work to keep the JS model aligned; that can of worms will be opened up either way when we start thinking about additional consistency modes.

**Comment by dschuff** [comment]
> Yeah, this deeply concerns me. Basically it means that we would not be able to add other atomics without some sort of global memory-model opt-in, because we'd break existing code otherwise. That seems highly undesirable, for all the reasons that non-local semantic modes are bad and unmodular.

You mean that code compiled against the current memory model would break when run in an implementation supporting a future memory model? 
Currently sequentially-consistent atomics are not allowed to be reordered with any other (even non-atomic) memory operations, and a future memory model would have to preserve that property (and presumably extend it to also imply that current-atomics not be reordered past future-atomics).
If it does that, I don't see how that code would break even if we add future-atomics (sequentially-consistent or otherwise) which may have looser constraints with respect to non-atomics (as C++ atomics do).

If the future memory model does not preserve that property, then that code would break; that includes code that never had any fences in the first place, e.g. code such as Figure 1 of the [Boehm paper](https://www.hpl.hp.com/techreports/2012/HPL-2012-68.pdf) (assuming it was not broken by mid-level LLVM optimizations) would work with the current semantics, and would break if we relaxed the atomic<->non-atomic ordering restriction even for seq_cst atomics.
So it's not clear to me how adding a fence to current wasm would help in that case.

Or did you mean that C++ code tested against wasm's current very strong memory model (rather than with strictly C++ semantics) would stop working when recompiled against the future memory model?

As an aside, there's not any technically-incorrect fence-using code in the boehm paper, but one kind of code I definitely expect to see in the real world is code written to a model like the [Linux Kernel memory model](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0124r2.html). In this model atomic loads/stores are not ordered wrt non-atomic loads/stores, but a full-barrier fence such as `smp_mb` in this model (and indeed on all the hardware I'm familiar with) synchronizes with non-atomics as well as atomics. This matches what a no-op atomic would do in wasm but does not really match anything in standard C++.

**Comment by conrad-watt** [comment]
The problem potentially comes when composing modules together which were compiled at different times.

Here's a very contrived example of the kind of problem that might arise when composing modules compiled before and after a hypothetical memory model extension.

Imagine the following C++ functions
```
void foo() {
  x.store(1, memory_order_seq_cst);
  y.store(1, memory_order_seq_cst);
}

int bar() {
  return y.load(memory_order_relaxed);
}

int baz() {
  atomic_thread_fence(memory_order_seq_cst);
  return x.load(memory_order_relaxed);
}
```
Let's imagine that all functions, as part of the following program, get compiled to Wasm under threads 1.0, and moreover that we are aggressive and no-op the fence. All atomic accesses are promoted to SC.
```
thread 1 | thread 2
 foo()   |  bar()
         |  baz()
```
For both C++, and the compiled Wasm, if bar() returns 1, then it must be the case that baz() is not allowed to return 0, and must return 1. This is the case even though the fence has been no-op'd.

To see this in C++ (the Wasm model is not too different), go to http://svr-pes20-cppmem.cl.cam.ac.uk/cppmem/index.html and paste in the following code:
```
int main() {
  atomic_int x = 0; atomic_int y = 0;

  // compiling all atomics to SC
  // fences no-op'd
  // baz()=0 not allowed

  {{{ // thread 1
      { // foo
        x.store(1, mo_seq_cst);
        y.store(1, mo_seq_cst); }

  ||| // thread 2
      { // bar()=1
        r1 = y.load(mo_seq_cst).readsvalue(1);

        // baz()=0
        r2 = x.load(mo_seq_cst).readsvalue(0); }
  }}};
  return 0; }
```

Now let's imagine that the Wasm memory model is extended with "relaxed atomics", and we swap out bar only for a recompiled version (call this bar_new) under a compiler supporting this new feature (you could imagine this as a proxy for some more complicated and better motivated composition of differently-compiled C++ modules). There is a version of this example for a release-acquire extension but it's harder to formulate.

Now, the load in bar_new remains a relaxed atomic.

```
thread 1 | thread 2
 foo()   |  bar_new()
         |  baz()
```

Now, the compiled Wasm no longer guarantees that if bar_new() returns 1, then baz() returns 1. The execution bar_new()=1, baz()=0 is allowed, which is weaker than the original code.

Again, http://svr-pes20-cppmem.cl.cam.ac.uk/cppmem/index.html lets us see this in C++
```
int main() {
  atomic_int x = 0; atomic_int y = 0;

  // bar_new compiled with relaxed atomics
  // baz()=0 allowed

  {{{ // thread 1
      { // foo
        x.store(1, mo_seq_cst);
        y.store(1, mo_seq_cst); }

  ||| // thread 2
      { // bar_new()=1
        r1 = y.load(mo_relaxed).readsvalue(1);

        // baz()=0
        r2 = x.load(mo_seq_cst).readsvalue(0); }
  }}};
  return 0; }

```

All this being said, I'm not sure even the current scheme (compiling fences to RMW) is strong enough to give the correct semantics in this example (after swapping in bar_new). I need to think about it more.

**Comment by dschuff** [comment]
Hm, I hadn't considered the case where modules are mixed in this way. From the toolchain perspective, it probably makes sense to consider these 2 modules as having different ABIs, and being incompatible (and therefore not linkable). In the toolchain space we are already dealing with the problem of helping users deal with different ABIs (used both within and across different wasm feature versions). See for example the [tar get features section](https://github.com/WebAssembly/tool-conventions/pull/99). We currently even also have special treatment for "no-threads" (where atomics are lowered away) vs threaded models, because it's harder on wasm (compared to other architectures) to share e.g. the same library code, and the no-threads case is more important on the web than other targets.
I'd be tempted to consider relaxed-atomics to be a different memory model from either of those, and refuse to link incompatible modules.

More generally, wasm and the web have a larger variety of ways for modules to share memories than native platforms (e.g. separate JS instances or ES modules which import the same memory). IIRC we already force modules to declare that their memory is shared (in the threads sense) or not, and don't allow instances to share memories (in the sense of importing the same memory, e.g. dynamic libraries) if they don't match. It might make sense to do that for relaxed-atomics too.

**Comment by lars-t-hansen** [comment]
Even though this gets us into the weeds of versioning and worse, perhaps this means that the memory object itself is parameterized by the memory model or memory model feature we expect to be used to access it?  Having a tool convention won't help us much, we need something in the core if we're going to truly prevent mismatches.
```
(memory 1 100 shared has-relaxed) ;; that's a list of attributes at the end
```
One wonders whether "memory attributes" might not be usable in other ways.  It's a known problem that on some 64-bit systems, having a lot of 6GB memory reservations can exhaust the OS's virtual address space (a problem on Linux aarch64; Windows Vista).  We've discussed having an attribute that says that the memory is not used intensively so as to allow code that uses it to be compiled with explicit bounds checking and not need the 6GB reservation:
```
(memory 1 100 optimize-for-space)
```

**Comment by conrad-watt** [comment]
Just to confirm, the current atomic RMW scheme isn't forwards-compatible either. Maybe this is something that could be discussed in the in-person meeting. My personal feeling is that it would be nice if each introduction of a new Wasm access consistency mode didn't imply "ABI incompatibility" in @dschuff's sense. Versioning a memory's model via a type-like annotation seems very close to versioning the module as a whole, which also feels desirable to avoid.

A possible solution would be adding a fence instruction to Wasm now, so that C/C++ fences could have something at the Wasm level to target. The fence instruction's semantics could then be updated (in a backwards-compatible way) to interact correctly with new consistency modes as they're spec'd. Implementers would just always compile the instruction like an [SC fence](https://www.cl.cam.ac.uk/~pes20/cpp/cpp0xmappings.html). There would be the potential for weaker fences later; this also wouldn't be ABI incompatible.

Ideally this would be added to JS too, but that would only be important for supporting someone compiling C to JS and trying to interop it with Wasm-compiled C in a C-semantics-preserving way. This case might more straightforwardly be ruled a ABI mismatch, in which case the instruction is only needed in Wasm.

When I'm thinking of ABI incompatibility here, I'm thinking of "programmatically, they can be linked (imported), but you won't preserve the original source semantics".

**Comment by lars-t-hansen** [comment]
That's interesting and useful.  Thanks.

The main argument for adding fence to JS in this case is not that one would "compile C to JS", but to ensure that, if JS and wasm interact, and there are synchronization operations that they both need to use to interact safely, and that would be implemented in both languages for performance reasons (ie no cross-language calls to access the operations), then those operations can be implemented equivalently in both languages in every case.

**Comment by dschuff** [comment]
Thanks for coming back to this again @conrad-watt. I think I like that idea. I had been afraid there might be resistance to the idea of adding more operations to the spec at this point but I think it will be worth it. I do think that it will be important that we add more relaxed memory operations in the future, since the current ones are so expensive. Now is actually a good time to be figuring this out because the upstream LLVM backend is about to be getting more wide distribution with emscripten very soon. So we should definitely discuss it at the in-person meeting.

Regarding JS, I think in one sense it does make sense to keep it as a mirror to wasm to allow the kind of cross-language application @lars-t-hansen mentioned. Regardless though, it will be tricky to reason about, because a developer will have to consider both the C memory model and the wasm/JS model (and how C lowers to wasm) in order to know that their program is correct; (especially given how the C++ memory model differs in respect to which operations synchronize with a particular atomic operation).

**Comment by aheejin** [comment]
We [decided](https://github.com/WebAssembly/meetings/blob/master/2019/CG-06.md#add-fence-instruction--hr) to implement `atomic.fence` instruction in the June CG meeting. I think the implementation has mostly done:

V8: v8/v8@4ca8b4dd67d79b3f5cd35441b07196811ab7aec9
Firefox: mozilla/gecko-dev@2094ef29281d0920b7ec1cfee4438150cd33079b
LLVM: llvm/llvm-project@d85fd5a3f42777bb53835a380b27a796262d434b
Binaryen: WebAssembly/binaryen#2307

So I'll close the issue.
