### ISSUE TITLE
"Merging" of global sections

### ISSUE THREAD

**Issue by pipcet** [WebAssembly/tool-conventions#8]
I think that phrase is somewhat ambiguous:

Data segments and table sections need to be merged by concatenation+renumbering.

The code section can be merged that way, too, though it's not clear to me whether a linker should, should be allowed to, or shouldn't collapse identical function bodies to the same function index (but not the same table index).

But for globals, doesn't it depend on the global whether the right thing to do is to concatenate the global entries (such as for unrelated globals) or make them refer to the same combined global (such as for the stack pointer)? In C terms, the same global variable in different CUs should be made to refer to the same memory location/wasm global, right?

Even if the approach we choose is to concatenate global entries in general, I don't see anything specific about the stack pointer that justifies giving it, but no other global, a special section to indicate it should be collapsed.

So the specific proposal is to replace "merging" by "concatenation" or "collapsing" in Linking.md; the less specific proposal is to get rid of the stack pointer special case and replace it with a generic way of merging "common" globals by name, rather than id.

**Comment by sunfishcode** [comment]
In general, for globals, we want concatenation.

We will eventually want support for weak/linkonce/comdat-like things, which I expect will take the form of additional symbol-table-like sections that supplement exports and imports.

For the stack pointer, what we really want to do is have every .o file just import the stack pointer, and have a crt1.o provide an exported definition for it. We can't do that right now because wasm doesn't support mutable globals in imports/exports. However, this restriction should be lifted before too long, as it'll likely happen along with the introduction of threads. So our hope is, that the special case of the stack pointer can be eliminated once that happens.

Also, I generally agree that "concatenation" would be clearer than "merging" when that's what's being done.

**Comment by pipcet** [comment]
It's unclear to me how that would deal with (non-weak/comdat, just regular C) common objects:

CU 1:
```
#include <stdio.h>

int a;

int main(void)
{
    printf("%d\n", a);
}
```

CU2:
```
int a = 3;
```

**Comment by pipcet** [comment]
And thanks for the response! I had been under the impression the "only immutable global variables can be imported" restriction had been lifted, so I was also curious why it wasn't done that way already.

The other section that I'm not sure about is the "type"/id=1 section. Is the linker expected to collapse identical entries? If yes, this should probably be spelled out; if no, won't that cause trouble when making an indirect call to a function pointer that might point to a function defined in two different modules?

Here's my current understanding of what a linker would do by section. Is that correct?
- Type (id=1) sections: concatenate, re-numbering signatures. Collapse identical signatures?
- Import (id=2) sections: concatenate, re-numbering imports, retaining only unresolved imports
- Function (id=3) sections: concatenate, re-numbering functions, potentially collapsing identical functions
- Table (id=4) sections: merge, collapsing everything into a single table in the MVP
- Memory (id=5) sections: merge, collapsing everything into a single memory in the MVP
- Global (id=6) sections: concatenate, re-numbering globals, but collapsing the stack pointer to a single global (see Linking Metadata)
- Export (id=7) sections: concatenate, re-numbering exports
- Start (id=8) sections: ???
- Element (id=9) sections: concatenate, re-numbering elements
- Code (id=10) sections: concatenate, re-numbering functions, potentially collapsing identical functions
- Data (id=11) sections: concatenate, re-positioning data
- Name (id=`"name"`) sections: concatenate, re-numbering functions; potentially collapse identical functions' names.

**Comment by sunfishcode** [comment]
Under traditional Unix rules, that's a "common block", which I meant to include in the category of weak/comdat/linkonce.

In the clang toolchain, we currently have the equivalent of -fno-common enabled by default when targeting wasm. It's fairly rare for code to need that old rule these days, and it simplifies several things if we don't have to support it. Once we design support for weak/comdat/linkonce/common/etc. we can revisit that decision.

**Comment by pipcet** [comment]
Ah, sorry about that. I should have realized you were including it. You're right that it's uncommon these days, as far as I can tell, so that's a sensible decision to have made for now.

**Comment by sunfishcode** [comment]
The summary of each section you listed above looks mostly right to me. For start sections, my first thought is that we could just fail to link if there are multiple start functions present.

One detail is that the relocations currently defined in Linking.md are meant to be sufficient so that a linker doesn't have to understand the code section; it can find all the places where indices need to be rewritten through the relocations and fix them up, rather like a regular linker. In theory this simplifies the linker's job (since it already has to process relocations to relocate things like address literals), but it's not something we've thought deeply about.

An open question is whether we want the linker to understand things like the element section, or if we just want relocations for those too.

@sbc100, what do you think?

**Comment by sbc100** [comment]
The summary looks about right to me too.

For the start section we might even want to completely disallow it, and rely on the normal behavior of requiring a specially named '_start' symbol (overridable via ld's --entry flag).

**Comment by sbc100** [comment]
The current implementation in lld has shift now such that all sections others than CODE and DATA as essentially synthesized based on the functions and data segements in the final output.   i.e. the input bytes are ignored for all sections except CODE and DATA, which use concatenation + relocations. 

We do should probably update Linking.md.
